# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[ 0.3629,  0.2971, -0.4378],
        [-0.3831, -0.0703, -0.2368]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([ 0.1267, -0.5408], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[-0.2295, -1.7749],
        [ 0.4373, -3.8456]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0]])
input_tensor

tensor([[6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Forward Pass: Binary Classification

In [19]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[-0.8435, -0.5717, -0.4649,  1.6803,  0.8372, -1.0154],
        [ 0.0316,  0.0263,  1.6489,  1.0859,  1.0566, -0.5965],
        [ 1.2135, -1.0728,  0.8688, -0.2424,  1.8248, -1.5248],
        [-1.3354, -1.1540,  0.1303, -0.1159,  0.4519,  0.4743],
        [-0.9881,  0.5731, -0.9582,  1.5397,  0.4616, -1.8293]])

In [20]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.5248],
        [0.4792],
        [0.3838],
        [0.5791],
        [0.5691]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [21]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.1898, -0.3346,  0.8670, -1.8370,  1.2096, -0.7538],
        [ 0.8806,  0.6602,  0.4566,  0.4660, -0.2459, -0.6900],
        [ 0.2391, -1.1145,  0.5660, -1.0716,  0.0662,  1.7749],
        [-0.5979, -0.1126, -1.5371,  0.2243, -0.0165, -0.4791],
        [ 0.2256, -2.5998,  1.1459, -1.4152,  0.1162,  0.0247]])

In [22]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.2921, 0.2834, 0.4245],
        [0.3347, 0.2092, 0.4561],
        [0.3324, 0.3692, 0.2984],
        [0.3080, 0.2559, 0.4361],
        [0.2808, 0.4011, 0.3181]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [23]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 1.3599,  0.5819, -0.5071, -2.0135,  1.4727,  0.2025],
        [-1.1500,  0.4500,  0.1780, -0.9129, -0.0241, -1.1357],
        [-0.0402,  0.9335,  0.0972, -0.5494,  0.0598,  2.3861],
        [ 0.6419,  2.0740, -0.4401,  0.7837, -0.4616, -1.5495],
        [ 1.6521, -1.9682,  0.3578,  0.1638, -0.3045,  0.2320]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[ 0.4482],
        [ 0.0046],
        [ 0.1754],
        [ 0.8648],
        [-0.2240]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [25]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [26]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [27]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [28]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

In [29]:
loss.backward

<bound method Tensor.backward of tensor(9.8222, dtype=torch.float64)>

## Sample Dataset

#### Load sample dataset

In [30]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [31]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [32]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [33]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [34]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])