# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[-0.4759, -0.4492,  0.4630],
        [ 0.1721, -0.2383, -0.3269]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([ 0.1040, -0.5120], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[ 0.1189, -1.7972],
        [-1.2672, -2.9764]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0]])
input_tensor

tensor([[6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Forward Pass: Binary Classification

In [19]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[-0.0493,  0.2349,  0.0575,  0.1812,  0.7690, -1.1840],
        [-0.5715, -0.4963,  0.7690,  0.5094, -0.8230,  0.6465],
        [ 0.2710, -1.4526,  0.1799,  1.1991, -0.8643, -0.2554],
        [ 0.0390,  0.2828, -0.9615, -0.9978, -1.7932, -0.0247],
        [-1.5256,  0.5329, -1.1191,  1.0852,  1.6259,  0.1598]])

In [20]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.4233],
        [0.4647],
        [0.4049],
        [0.4404],
        [0.2797]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [21]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.5238,  0.3844, -0.2193,  0.2946, -0.0363,  1.0298],
        [-0.2556, -0.5737, -1.4697, -0.9670,  0.3977, -0.1808],
        [ 1.0324,  0.8041,  1.0593, -0.5407,  0.1779,  0.7868],
        [ 0.8270,  1.2138,  0.5281, -0.8974,  0.6325, -2.0965],
        [ 1.0463,  0.2363,  0.4138,  0.3090,  0.2342,  0.3745]])

In [22]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.3981, 0.2578, 0.3441],
        [0.4433, 0.1981, 0.3586],
        [0.3550, 0.4000, 0.2449],
        [0.4332, 0.2815, 0.2853],
        [0.3820, 0.3214, 0.2967]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [23]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 1.1856,  0.2214,  0.2315,  0.6581,  1.6583,  0.2342],
        [-0.2489,  1.1059, -0.6619,  0.3173,  2.0536, -0.4081],
        [ 0.2808,  0.2156,  0.1698,  0.2079, -0.2206, -0.3520],
        [ 0.1776,  1.3047,  0.0145, -0.4112,  2.6018, -0.2342],
        [-0.1534,  1.3752, -1.5663, -1.2651, -1.7240,  0.2818]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[-0.3269],
        [-0.3697],
        [-0.0779],
        [-0.6206],
        [ 0.0049]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [25]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [26]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [27]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [28]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

In [29]:
loss.backward

<bound method Tensor.backward of tensor(9.8222, dtype=torch.float64)>

## Sample Dataset

#### Load sample dataset

In [30]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [31]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [32]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [33]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [34]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])

#### TensorDataset

In [35]:
from torch.utils.data import TensorDataset
from torch import tensor

dataset = TensorDataset(tensor(X), tensor(y))
dataset

In [36]:
input_sample, label_sample = dataset[0]
print(f"input_sample: {input_sample}")
print(f"label_sample: {label_sample}")


input_sample: tensor([0, 1, 1, 0, 0, 2, 1])
label_sample: 0


#### DataLoader

In [37]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [38]:
for batch_inputs, batch_labels in dataloader:
    print(f"batch_inputs: {batch_inputs}")
    print(f"batch_labels: {batch_labels}")
    print("=" * 50)

batch_inputs: tensor([[0, 1, 1, 0, 0, 2, 1],
        [1, 0, 0, 1, 1, 4, 1]])
batch_labels: tensor([0, 1])
batch_inputs: tensor([[0, 0, 1, 0, 1, 4, 1],
        [1, 0, 0, 1, 0, 4, 1]])
batch_labels: tensor([2, 1])
batch_inputs: tensor([[0, 1, 1, 0, 1, 2, 1]])
batch_labels: tensor([0])
