# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[-0.4439, -0.2162,  0.5640],
        [-0.1689, -0.3409, -0.5456]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([-0.3449,  0.3514], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[ 0.4707, -2.1360],
        [ 0.1824, -5.3021]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0, -6.0]])
input_tensor

tensor([[ 6., -6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975, 0.0025]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Activation Layer: ReLU (Rectified Linear Unit)

In [19]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [20]:
relu_layer = nn.ReLU()
relu_layer(input_tensor)

tensor([[4.3000, 6.1000, 0.0000]])

### Activation Layer: Leaky ReLU 

In [21]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [22]:
leaky_relu = nn.LeakyReLU(negative_slope=0.05)
leaky_relu(input_tensor)

tensor([[ 4.3000,  6.1000, -0.1150]])

### Forward Pass: Binary Classification

In [23]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[ 0.7295,  0.6402,  0.4143, -0.1720,  0.5636, -0.5427],
        [-0.1814, -0.0786,  0.1527, -1.1849,  0.0414, -0.0802],
        [ 0.4204,  0.6533, -0.5800,  0.7627, -0.3448, -0.9283],
        [ 0.8224,  0.2168,  1.9888,  0.3427, -0.1392, -0.9059],
        [-0.9725, -1.1209,  0.6076,  3.0988, -0.6038,  0.0088]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.4318],
        [0.5076],
        [0.4073],
        [0.5130],
        [0.3491]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [25]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[-2.1726, -1.3209,  0.5447,  0.8764,  0.9054, -2.2942],
        [-0.0074, -0.5285,  0.0174,  1.3431,  1.7263,  0.5185],
        [-0.9119, -0.4187, -0.4418,  1.6232,  1.9412, -1.2688],
        [-0.4566,  0.0484, -0.2832, -0.4436, -0.1682, -1.5368],
        [-2.0466,  0.0573, -1.1413, -1.2204,  0.4023,  0.0971]])

In [26]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.2658, 0.5054, 0.2288],
        [0.4129, 0.3270, 0.2601],
        [0.4066, 0.3766, 0.2168],
        [0.4042, 0.2110, 0.3848],
        [0.4123, 0.1347, 0.4530]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [27]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[-1.3214, -0.5548,  0.5598,  0.2282, -2.0190, -1.4704],
        [-1.2057, -0.7482,  1.0416, -0.8981, -0.9198, -1.0017],
        [ 0.3577, -2.2936, -0.1064,  0.9290,  1.2568,  0.2319],
        [ 1.9484,  0.3674,  0.1866,  1.1145, -0.5228, -0.5065],
        [-1.5930,  1.5937,  0.3777,  0.6551,  0.3123,  1.0536]])

In [28]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[-0.7109],
        [-0.7785],
        [-0.3981],
        [-0.9543],
        [-0.5168]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [29]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [30]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [31]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [32]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

## Sample Dataset

#### Load sample dataset

In [33]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [34]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [35]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [36]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [37]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])

#### TensorDataset

In [38]:
from torch.utils.data import TensorDataset
from torch import tensor

dataset = TensorDataset(tensor(X), tensor(y))
dataset

In [39]:
input_sample, label_sample = dataset[0]
print(f"input_sample: {input_sample}")
print(f"label_sample: {label_sample}")

input_sample: tensor([0, 1, 1, 0, 0, 2, 1])
label_sample: 0


#### DataLoader

In [40]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [41]:
for batch_inputs, batch_labels in dataloader:
    print(f"batch_inputs: {batch_inputs}")
    print(f"batch_labels: {batch_labels}")
    print("=" * 50)

batch_inputs: tensor([[1, 0, 0, 1, 1, 4, 1],
        [1, 0, 0, 1, 0, 4, 1]])
batch_labels: tensor([1, 1])
batch_inputs: tensor([[0, 0, 1, 0, 1, 4, 1],
        [0, 1, 1, 0, 1, 2, 1]])
batch_labels: tensor([2, 0])
batch_inputs: tensor([[0, 1, 1, 0, 0, 2, 1]])
batch_labels: tensor([0])


## Training Loop

### Load Salary Dataset

In [42]:
import pandas as pd

salary = pd.read_csv("salary_dataset.csv")
salary

experience_level   employment_type   remote_ratio   company_size  \
0                 0                 0            0.5              1   
1                 1                 0            1.0              2   
2                 2                 0            0.0              1   
3                 1                 0            1.0              0   
4                 2                 0            1.0              1   

    salary_in_usd  
0           0.036  
1           0.133  
2           0.234  
3           0.076  
4           0.170

### Features & Target

In [43]:
features = salary.iloc[:, :-1]
features

experience_level   employment_type   remote_ratio   company_size
0                 0                 0            0.5              1
1                 1                 0            1.0              2
2                 2                 0            0.0              1
3                 1                 0            1.0              0
4                 2                 0            1.0              1

In [44]:
X = features.to_numpy()
X

array([[0. , 0. , 0.5, 1. ],
       [1. , 0. , 1. , 2. ],
       [2. , 0. , 0. , 1. ],
       [1. , 0. , 1. , 0. ],
       [2. , 0. , 1. , 1. ]])

In [45]:
target = salary.iloc[:, -1]
target

0    0.036
1    0.133
2    0.234
3    0.076
4    0.170
Name:  salary_in_usd, dtype: float64

In [46]:
y = target.to_numpy()
y

array([0.036, 0.133, 0.234, 0.076, 0.17 ])

### Tensor Dataset & DataLoader

In [47]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataset

In [48]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

### Model, Loss Function & SDG (Stochastic Gradient Descent) Optimizer

In [49]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))

# Loss Function a.k.a Criterion
criterion = nn.MSELoss()

# learning rate controls the step size
# typical range between 0.01 and 0.0001
learning_rate = 0.001

# momentum helps escape local optima
# typical range between 0.85 and 0.99
momentum = 0.8

optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)

### The Training Loop

In [50]:
num_epochs = 10

for epoch in range(num_epochs):
    for data in dataloader:
        optimizer.zero_grad()

        feature, target = data
        pred = model(feature)
        # Reshape target to match prediction shape
        target = target.view(-1, 1)

        loss = criterion(pred, target)
        loss.backward()
        optimizer.step()

## Layer Initialization & Transfer Learning

In [51]:
from torch import nn

linear_layer = nn.Linear(64, 128)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: -0.12499947845935822
max weight: 0.12499257922172546


### Uniform Wight Initialization

In [52]:
from torch import nn

linear_layer = nn.Linear(64, 128)
nn.init.uniform_(linear_layer.weight)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: 8.487701416015625e-05
max weight: 0.9998798370361328


### Transfer Learning: Fine-tuning

In [53]:
import torch

some_pretrained_layer = nn.Sequential(
    nn.Linear(256, 32), 
    nn.Linear(32, 64), 
    nn.Linear(64, 128)
)
torch.save(some_pretrained_layer, "some_pretrained_layer.pth")

#### Freeze layers of a pretrained model

In [54]:
import torch
from torch import nn

pretrained_layer = torch.load("some_pretrained_layer.pth")
for name, param in pretrained_layer.named_parameters():
    # Check for first layer's weight
    if name == "0.weight":
        # Freeze this weight
        param.requires_grad = False

    # Check for second layer's weight
    if name == "1.weight":
        # Freeze this weight
        param.requires_grad = False

#### Add more layers of a pretrained model

In [55]:
modified_layer = nn.Sequential(
    pretrained_layer, nn.Linear(128, 256), nn.Linear(256, 64)
)