# Introduction to PyTorch part 1

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[ 0.5654, -0.1546,  0.5315],
        [-0.1639,  0.2187, -0.4769]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([0.2892, 0.2398], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[ 2.1399, -0.9175],
        [ 4.9668, -2.1840]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0, -6.0]])
input_tensor

tensor([[ 6., -6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975, 0.0025]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Activation Layer: ReLU (Rectified Linear Unit)

In [19]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [20]:
relu_layer = nn.ReLU()
relu_layer(input_tensor)

tensor([[4.3000, 6.1000, 0.0000]])

### Activation Layer: Leaky ReLU 

In [21]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [22]:
leaky_relu = nn.LeakyReLU(negative_slope=0.05)
leaky_relu(input_tensor)

tensor([[ 4.3000,  6.1000, -0.1150]])

### Forward Pass: Binary Classification

In [23]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[-0.3798,  0.1431,  0.4692, -0.6007, -1.0169, -0.5017],
        [-1.6565,  0.4586, -0.9228,  0.8816,  0.2521,  0.1027],
        [ 1.5725,  0.3321,  1.7892, -1.7630,  0.8406,  0.9841],
        [-1.1737,  0.5918, -0.3279,  1.0038, -0.9965, -0.1920],
        [ 1.5729, -0.0076,  0.6817,  0.0985,  1.5555, -0.0986]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.2791],
        [0.3626],
        [0.4585],
        [0.3332],
        [0.4562]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [25]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.0648,  0.0732,  0.4037, -1.2401,  1.2099, -0.4360],
        [-0.8194, -0.6346, -1.5734, -0.7075, -0.4399, -2.3645],
        [ 0.0849, -0.7814, -1.7637, -1.9324,  0.2971,  0.3875],
        [ 0.2284, -0.4769, -0.6267,  0.2425,  0.0534, -0.8669],
        [ 0.6863,  0.4283,  1.3912,  1.2285, -0.3701, -0.8859]])

In [26]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.4376, 0.1837, 0.3787],
        [0.2907, 0.2987, 0.4106],
        [0.3655, 0.3043, 0.3302],
        [0.3753, 0.2199, 0.4048],
        [0.4088, 0.1630, 0.4282]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [27]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 1.9850, -1.4703,  0.8986,  0.5196, -0.8939,  3.0478],
        [ 0.6509, -0.4813, -0.0890,  0.1570,  0.1906,  0.4888],
        [-0.9788, -1.4445,  0.2660,  0.3458, -1.5452, -0.7408],
        [-1.0880, -0.4685,  0.8671,  0.4116,  0.6516, -0.4323],
        [ 0.9517,  0.2000,  0.2553, -1.8860, -0.0228,  0.1318]])

In [28]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[0.6062],
        [0.2267],
        [0.1619],
        [0.0242],
        [0.5888]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [29]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [30]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [31]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [32]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

## Sample Dataset

#### Load sample dataset

In [33]:
import pandas as pd

animals = pd.read_csv("./data/animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [34]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [35]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [36]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [37]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])

#### TensorDataset

In [38]:
from torch.utils.data import TensorDataset
from torch import tensor

dataset = TensorDataset(tensor(X), tensor(y))
dataset

In [39]:
input_sample, label_sample = dataset[0]
print(f"input_sample: {input_sample}")
print(f"label_sample: {label_sample}")

input_sample: tensor([0, 1, 1, 0, 0, 2, 1])
label_sample: 0


#### DataLoader

In [40]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [41]:
for batch_inputs, batch_labels in dataloader:
    print(f"batch_inputs: {batch_inputs}")
    print(f"batch_labels: {batch_labels}")
    print("=" * 50)

batch_inputs: tensor([[0, 1, 1, 0, 0, 2, 1],
        [0, 0, 1, 0, 1, 4, 1]])
batch_labels: tensor([0, 2])
batch_inputs: tensor([[1, 0, 0, 1, 0, 4, 1],
        [1, 0, 0, 1, 1, 4, 1]])
batch_labels: tensor([1, 1])
batch_inputs: tensor([[0, 1, 1, 0, 1, 2, 1]])
batch_labels: tensor([0])


## Training Loop

### Load Salary Dataset

In [42]:
import pandas as pd

salary = pd.read_csv("./data/salary_dataset.csv")
salary

experience_level   employment_type   remote_ratio   company_size  \
0                 0                 0            0.5              1   
1                 1                 0            1.0              2   
2                 2                 0            0.0              1   
3                 1                 0            1.0              0   
4                 2                 0            1.0              1   

    salary_in_usd  
0           0.036  
1           0.133  
2           0.234  
3           0.076  
4           0.170

### Features & Target

In [43]:
features = salary.iloc[:, :-1]
features

experience_level   employment_type   remote_ratio   company_size
0                 0                 0            0.5              1
1                 1                 0            1.0              2
2                 2                 0            0.0              1
3                 1                 0            1.0              0
4                 2                 0            1.0              1

In [44]:
X = features.to_numpy()
X

array([[0. , 0. , 0.5, 1. ],
       [1. , 0. , 1. , 2. ],
       [2. , 0. , 0. , 1. ],
       [1. , 0. , 1. , 0. ],
       [2. , 0. , 1. , 1. ]])

In [45]:
target = salary.iloc[:, -1]
target

0    0.036
1    0.133
2    0.234
3    0.076
4    0.170
Name:  salary_in_usd, dtype: float64

In [46]:
y = target.to_numpy()
y

array([0.036, 0.133, 0.234, 0.076, 0.17 ])

### Tensor Dataset & DataLoader

In [47]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataset

In [48]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

### Model, Loss Function & SDG (Stochastic Gradient Descent) Optimizer

In [49]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))

# Loss Function a.k.a Criterion
criterion = nn.MSELoss()

# learning rate controls the step size
# typical range between 0.01 and 0.0001
learning_rate = 0.001

# momentum helps escape local optima
# typical range between 0.85 and 0.99
momentum = 0.8

optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)

### The Training Loop

In [50]:
num_epochs = 10

for epoch in range(num_epochs):
    for data in dataloader:
        feature, target = data

        # Run the forward pass
        pred = model(feature)

        # Reshape target to match prediction shape
        target = target.view(-1, 1)
        # Compute the loss
        loss = criterion(pred, target)

        # Backpropagation
        loss.backward()  # Compute gradients
        optimizer.step()  # Update weights
        optimizer.zero_grad()  # Reset gradients

## Layer Initialization & Transfer Learning

In [51]:
from torch import nn

linear_layer = nn.Linear(64, 128)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: -0.12497636675834656
max weight: 0.12494617700576782


### Uniform Wight Initialization

In [52]:
from torch import nn

linear_layer = nn.Linear(64, 128)
nn.init.uniform_(linear_layer.weight)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: 5.441904067993164e-05
max weight: 0.9998668432235718


### Transfer Learning: Fine-tuning

In [53]:
import torch

some_pretrained_layer = nn.Sequential(
    nn.Linear(256, 32), nn.Linear(32, 64), nn.Linear(64, 128)
)
torch.save(some_pretrained_layer, "some_pretrained_layer.pth")

#### Freeze layers of a pretrained model

In [54]:
import torch
from torch import nn

pretrained_layer = torch.load("some_pretrained_layer.pth")
for name, param in pretrained_layer.named_parameters():
    # Check for first layer's weight
    if name == "0.weight":
        # Freeze this weight
        param.requires_grad = False

    # Check for second layer's weight
    if name == "1.weight":
        # Freeze this weight
        param.requires_grad = False

#### Add more layers of a pretrained model

In [55]:
modified_layer = nn.Sequential(
    pretrained_layer, nn.Linear(128, 256), nn.Linear(256, 64)
)

## Evaluating Model Performance

In [56]:
import pandas as pd

salary = pd.read_csv("./data/salary_dataset.csv")

features = salary.iloc[:, :-1]
X = features.to_numpy()

target = salary.iloc[:, -1]
y = target.to_numpy()

In [57]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [58]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.8)

### Training Loss & Epoch Loss

In [59]:
training_loss = 0.0

for feature, target in dataloader:
    # Run the forward pass
    pred = model(feature)

    # Reshape target to match prediction shape
    target = target.view(-1, 1)
    # Compute the loss
    loss = criterion(pred, target)

    # Backpropagation
    loss.backward()  # Compute gradients
    optimizer.step()  # Update weights
    optimizer.zero_grad()  # Reset gradients

    # Calculate and sum the loss
    training_loss += loss.item()

epoch_loss = training_loss / len(dataloader)
print(f"training loss: {training_loss}")
print(f"epoch loss: {epoch_loss}")

training loss: 0.27041108906269073
epoch loss: 0.13520554453134537


### Validation Loss

In [60]:
# Set model into evaluation mode
model.eval()

validation_loss = 0.0
with torch.no_grad():
    for feature, target in dataloader:
        # Run the forward pass
        pred = model(feature)

        # Reshape target to match prediction shape
        target = target.view(-1, 1)
        # Compute the loss
        loss = criterion(pred, target)

        # Calculate and sum the loss
        validation_loss += loss.item()

epoch_loss = validation_loss / len(dataloader)
print(f"training loss: {validation_loss}")
print(f"epoch loss: {epoch_loss}")

# Set model back into training mode
model.train()

training loss: 0.2651306539773941
epoch loss: 0.13256532698869705


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

Indication of model overfitting:
- training loss dreceasing
- validation loss increasing

### Using `torchmetrics`

In [61]:
import torchmetrics

# Initialize the metric
metric = torchmetrics.MeanSquaredError()

# Set model to evaluation mode
model.eval()

# Evaluate without computing gradients
with torch.no_grad():
    for feature, target in dataloader:
        # Get predictions
        pred = model(feature)

        # Reshape target to match prediction shape
        target = target.view(-1, 1)

        # Update metric
        metric.update(pred, target)

# Compute final metric
mse = metric.compute()
print(f"Mean Squared Error: {mse:.4f}")

# Reset metric for future use
metric.reset()

# Set model back to training mode
model.train()

Mean Squared Error: 0.1406


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

## Fighting Overfitting: Regularization

### Regularization with Dropout Layer

Dropout Layer, randomly zeroes out elements of the input tensor during training preventing the model from becoming too dependent on specific features.

In [62]:
import torch
from torch import nn

model = nn.Sequential(nn.Linear(8, 4), nn.ReLU(), nn.Dropout(p=0.5))
features = torch.randn((1, 8))
predictions = model(features)
predictions

tensor([[0.0000, 0.7475, 0.0000, 0.0000]], grad_fn=<MulBackward0>)

### Regularization with Weight Decay

Weight Decay encourages smaller weights by adding a penalty during optimization. <br/>
It helps reduce overfitting by keeping weights smaller and improving generalization.

In [63]:
import torch
from torch import nn, optim

model = nn.Sequential(nn.Linear(8, 4), nn.ReLU())
optimizer = optim.SGD(model.parameters(), lr=0.001, weight_decay=0.0001)

features = torch.randn((1, 8))
predictions = model(features)
predictions

tensor([[0.6820, 0.0000, 0.3913, 0.0000]], grad_fn=<ReluBackward0>)