# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[ 0.3968, -0.0839, -0.3267],
        [ 0.1878,  0.3049,  0.1012]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([ 0.3248, -0.0193], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[-0.4264,  1.0820],
        [-0.4680,  2.8637]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0, -6.0]])
input_tensor

tensor([[ 6., -6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975, 0.0025]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Activation Layer: ReLU (Rectified Linear Unit)

In [19]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [20]:
relu_layer = nn.ReLU()
relu_layer(input_tensor)

tensor([[4.3000, 6.1000, 0.0000]])

### Activation Layer: Leaky ReLU 

In [21]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, -2.3]])
input_tensor

tensor([[ 4.3000,  6.1000, -2.3000]])

In [22]:
leaky_relu = nn.LeakyReLU(negative_slope=0.05)
leaky_relu(input_tensor)

tensor([[ 4.3000,  6.1000, -0.1150]])

### Forward Pass: Binary Classification

In [23]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[-1.4199,  0.2206,  2.2733,  1.0084,  0.4885,  0.7045],
        [-2.1638, -0.4430, -0.0183,  1.3667,  0.7258, -0.6101],
        [-1.2362,  0.7299,  1.5206, -0.0604, -1.0238,  0.3472],
        [ 0.7501,  0.0229,  1.1817,  0.9888, -0.7528, -0.2778],
        [-0.5022,  0.2803, -0.7087, -0.5284,  0.0694,  1.0269]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.3088],
        [0.3265],
        [0.3408],
        [0.4784],
        [0.4846]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [25]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.7744,  0.8116, -0.2964, -0.6585, -0.2238,  0.0916],
        [ 0.9157, -0.0631, -2.8924,  0.2714, -1.1245,  2.2704],
        [-2.5592, -0.9494, -0.4142, -0.7723, -0.7420,  0.2149],
        [ 0.8153,  0.3823, -0.8152,  0.9533, -0.8013,  0.8831],
        [-1.3211, -1.3198, -2.2298,  1.9752, -0.3518, -1.1392]])

In [26]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.3672, 0.2048, 0.4280],
        [0.3527, 0.3857, 0.2615],
        [0.4435, 0.1894, 0.3671],
        [0.2841, 0.3500, 0.3659],
        [0.5066, 0.2593, 0.2341]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [27]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[-1.2404, -0.0706,  0.4921,  0.5803, -0.8286,  1.6709],
        [-1.7669, -0.6682,  0.3349, -1.3040, -0.7395,  0.6290],
        [-0.2349,  0.3806,  0.1772, -0.0917, -1.5503, -0.3516],
        [ 0.2104, -1.3553, -0.2489, -0.2220, -0.9151, -0.7220],
        [ 0.3846,  1.3596,  1.3821, -1.9348, -0.5376, -0.2730]])

In [28]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[ 0.0126],
        [ 0.1774],
        [-0.0675],
        [-0.4000],
        [ 0.1507]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [29]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [30]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [31]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [32]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

## Sample Dataset

#### Load sample dataset

In [33]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [34]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [35]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [36]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [37]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])

#### TensorDataset

In [38]:
from torch.utils.data import TensorDataset
from torch import tensor

dataset = TensorDataset(tensor(X), tensor(y))
dataset

In [39]:
input_sample, label_sample = dataset[0]
print(f"input_sample: {input_sample}")
print(f"label_sample: {label_sample}")

input_sample: tensor([0, 1, 1, 0, 0, 2, 1])
label_sample: 0


#### DataLoader

In [40]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [41]:
for batch_inputs, batch_labels in dataloader:
    print(f"batch_inputs: {batch_inputs}")
    print(f"batch_labels: {batch_labels}")
    print("=" * 50)

batch_inputs: tensor([[0, 0, 1, 0, 1, 4, 1],
        [1, 0, 0, 1, 1, 4, 1]])
batch_labels: tensor([2, 1])
batch_inputs: tensor([[0, 1, 1, 0, 1, 2, 1],
        [1, 0, 0, 1, 0, 4, 1]])
batch_labels: tensor([0, 1])
batch_inputs: tensor([[0, 1, 1, 0, 0, 2, 1]])
batch_labels: tensor([0])


## Training Loop

### Load Salary Dataset

In [42]:
import pandas as pd

salary = pd.read_csv("salary_dataset.csv")
salary

experience_level   employment_type   remote_ratio   company_size  \
0                 0                 0            0.5              1   
1                 1                 0            1.0              2   
2                 2                 0            0.0              1   
3                 1                 0            1.0              0   
4                 2                 0            1.0              1   

    salary_in_usd  
0           0.036  
1           0.133  
2           0.234  
3           0.076  
4           0.170

### Features & Target

In [43]:
features = salary.iloc[:, :-1]
features

experience_level   employment_type   remote_ratio   company_size
0                 0                 0            0.5              1
1                 1                 0            1.0              2
2                 2                 0            0.0              1
3                 1                 0            1.0              0
4                 2                 0            1.0              1

In [44]:
X = features.to_numpy()
X

array([[0. , 0. , 0.5, 1. ],
       [1. , 0. , 1. , 2. ],
       [2. , 0. , 0. , 1. ],
       [1. , 0. , 1. , 0. ],
       [2. , 0. , 1. , 1. ]])

In [45]:
target = salary.iloc[:, -1]
target

0    0.036
1    0.133
2    0.234
3    0.076
4    0.170
Name:  salary_in_usd, dtype: float64

In [46]:
y = target.to_numpy()
y

array([0.036, 0.133, 0.234, 0.076, 0.17 ])

### Tensor Dataset & DataLoader

In [47]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataset

In [48]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

### Model, Loss Function & SDG (Stochastic Gradient Descent) Optimizer

In [49]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))

# Loss Function a.k.a Criterion
criterion = nn.MSELoss()

# learning rate controls the step size
# typical range between 0.01 and 0.0001
learning_rate = 0.001

# momentum helps escape local optima
# typical range between 0.85 and 0.99
momentum = 0.8

optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=momentum)

### The Training Loop

In [50]:
num_epochs = 10

for epoch in range(num_epochs):
    for data in dataloader:
        feature, target = data

        # Run the forward pass
        pred = model(feature)

        # Reshape target to match prediction shape
        target = target.view(-1, 1)
        # Compute the loss
        loss = criterion(pred, target)

        # Backpropagation
        loss.backward() # Compute gradients
        optimizer.step() # Update weights
        optimizer.zero_grad() # Reset gradients

## Layer Initialization & Transfer Learning

In [51]:
from torch import nn

linear_layer = nn.Linear(64, 128)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: -0.12499792873859406
max weight: 0.12498028576374054


### Uniform Wight Initialization

In [52]:
from torch import nn

linear_layer = nn.Linear(64, 128)
nn.init.uniform_(linear_layer.weight)

print(f"min weight: {linear_layer.weight.min()}")
print(f"max weight: {linear_layer.weight.max()}")

min weight: 0.00023674964904785156
max weight: 0.9999375343322754


### Transfer Learning: Fine-tuning

In [53]:
import torch

some_pretrained_layer = nn.Sequential(
    nn.Linear(256, 32), 
    nn.Linear(32, 64), 
    nn.Linear(64, 128)
)
torch.save(some_pretrained_layer, "some_pretrained_layer.pth")

#### Freeze layers of a pretrained model

In [54]:
import torch
from torch import nn

pretrained_layer = torch.load("some_pretrained_layer.pth")
for name, param in pretrained_layer.named_parameters():
    # Check for first layer's weight
    if name == "0.weight":
        # Freeze this weight
        param.requires_grad = False

    # Check for second layer's weight
    if name == "1.weight":
        # Freeze this weight
        param.requires_grad = False

#### Add more layers of a pretrained model

In [55]:
modified_layer = nn.Sequential(
    pretrained_layer, nn.Linear(128, 256), nn.Linear(256, 64)
)

## Evaluating Model Performance

In [56]:
import pandas as pd

salary = pd.read_csv("salary_dataset.csv")

features = salary.iloc[:, :-1]
X = features.to_numpy()

target = salary.iloc[:, -1]
y = target.to_numpy()

In [57]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

In [58]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001, momentum=0.8)

### Training Loss & Epoch Loss

In [59]:
training_loss = 0.0

for feature, target in dataloader:
    # Run the forward pass
    pred = model(feature)

    # Reshape target to match prediction shape
    target = target.view(-1, 1)
    # Compute the loss
    loss = criterion(pred, target)

    # Backpropagation
    loss.backward() # Compute gradients
    optimizer.step() # Update weights
    optimizer.zero_grad() # Reset gradients

    # Calculate and sum the loss
    training_loss += loss.item()

epoch_loss = training_loss / len(dataloader)
print(f"training loss: {training_loss}")
print(f"epoch loss: {epoch_loss}")

training loss: 0.11202576942741871
epoch loss: 0.056012884713709354


### Validation Loss

In [60]:
# Set model into evaluation mode
model.eval() 

validation_loss = 0.0
with torch.no_grad():
    for feature, target in dataloader:
        # Run the forward pass
        pred = model(feature)

        # Reshape target to match prediction shape
        target = target.view(-1, 1)
        # Compute the loss
        loss = criterion(pred, target)

        # Calculate and sum the loss
        validation_loss += loss.item()

epoch_loss = validation_loss / len(dataloader)
print(f"training loss: {validation_loss}")
print(f"epoch loss: {epoch_loss}")

# Set model back into training mode
model.train()

training loss: 0.13953059911727905
epoch loss: 0.06976529955863953


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)

Indication of model overfitting:
- training loss dreceasing
- validation loss increasing

### Using `torchmetrics`

In [61]:
import torchmetrics

# Initialize the metric
metric = torchmetrics.MeanSquaredError()

# Set model to evaluation mode
model.eval()

# Evaluate without computing gradients
with torch.no_grad():
    for feature, target in dataloader:
        # Get predictions
        pred = model(feature)
        
        # Reshape target to match prediction shape
        target = target.view(-1, 1)
        
        # Update metric
        metric.update(pred, target)

# Compute final metric
mse = metric.compute()
print(f"Mean Squared Error: {mse:.4f}")

# Reset metric for future use
metric.reset()

# Set model back to training mode
model.train()

Mean Squared Error: 0.0722


Sequential(
  (0): Linear(in_features=4, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=1, bias=True)
)