# Introduction to Pytorch

## The Basics

### Tensor

In [1]:
from torch import tensor

/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [2]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])   
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [3]:
input_tensor.shape

torch.Size([2, 3])

In [4]:
input_tensor.dtype

torch.float32

### Linear Layer

In [5]:
from torch import nn

In [6]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [7]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0428,  0.3687,  0.5036],
        [-0.0474,  0.4790,  0.3780]], requires_grad=True)

In [8]:
linear_layer.bias

Parameter containing:
tensor([-0.5196,  0.5302], requires_grad=True)

In [9]:
output = linear_layer(input_tensor)
output

tensor([[1.7714, 2.5747],
        [4.5167, 5.0034]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [10]:
from torch import nn

In [11]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output)
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [20]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("="*50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")


24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [22]:
from torch import tensor, nn 

input_tensor = tensor([[6.0]])
input_tensor

sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)



tensor([[0.9975]])