# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/ipykernel/ker

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[ 0.4124, -0.3762, -0.2862],
        [-0.4957,  0.4480, -0.0078]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([0.0083, 0.0540], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[-1.1904,  0.4309],
        [-1.9404,  0.2644]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0]])
input_tensor

tensor([[6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Forward Pass: Binary Classification

In [19]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[ 1.1701,  0.9984,  1.1182,  1.0012, -0.3226, -0.8884],
        [ 0.2262, -1.5694,  0.4641,  0.7326, -0.8107, -1.3986],
        [ 0.5235,  0.6417,  0.9909, -1.0500,  1.1148, -0.7194],
        [ 2.2848, -0.2488,  0.4813, -0.1790,  0.9614,  0.1438],
        [ 0.7187,  0.7539, -0.0138,  1.3153,  0.1319,  0.7796]])

In [20]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.6687],
        [0.6745],
        [0.6338],
        [0.5305],
        [0.5848]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [21]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.3624,  0.4471,  0.7979, -1.0404, -0.3699,  0.5354],
        [-1.1568, -0.0810, -0.6738,  1.8299, -0.5462,  0.6445],
        [ 0.3677, -0.4180,  1.6743, -1.6039,  1.3070, -1.4045],
        [ 0.1299, -1.2020,  0.6944,  0.1132, -0.6622, -0.0993],
        [ 2.7031,  0.3668,  1.3368,  1.5064,  1.2778, -1.1405]])

In [22]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.3562, 0.3899, 0.2538],
        [0.1331, 0.5658, 0.3011],
        [0.5546, 0.2817, 0.1637],
        [0.2990, 0.4263, 0.2747],
        [0.3254, 0.3736, 0.3010]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [23]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.0628, -2.0075, -0.5695, -0.7480,  0.7923,  0.5137],
        [-0.8707,  0.2637,  0.5048, -0.0532,  1.3315,  0.0776],
        [-0.6981, -0.3680,  1.1737,  0.8421,  1.2120, -0.4832],
        [ 1.1758,  1.3709,  0.1610,  0.5656,  1.1099,  0.2550],
        [-0.6518, -0.3093,  1.0466,  0.0891,  0.4826, -0.1527]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[-0.2433],
        [-0.4369],
        [-0.4392],
        [-0.5283],
        [-0.2145]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [25]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [26]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [27]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [28]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

In [29]:
loss.backward

<bound method Tensor.backward of tensor(9.8222, dtype=torch.float64)>

## Sample Dataset

#### Load sample dataset

In [30]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [31]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [32]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [33]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [34]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])