# Introduction to PyTorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[ 0.0420,  0.5711, -0.1624],
        [-0.4095, -0.3720, -0.2236]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([-0.0410, -0.0978], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[ 0.6559, -1.9222],
        [ 2.0078, -4.9375]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0]])
input_tensor

tensor([[6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Forward Pass: Binary Classification

In [19]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[ 0.0983,  0.2869, -1.9218, -0.3181,  0.9870, -0.3007],
        [ 1.0820,  0.0606, -1.8228,  0.8030, -1.0552, -0.1279],
        [ 0.2592, -2.1780, -0.0826, -0.2428, -0.7621,  0.0038],
        [-0.1114,  0.6464,  0.8811, -0.1925,  2.6791, -0.9053],
        [ 0.1607, -0.9174,  1.0053, -1.0888,  0.4229,  0.5705]])

In [20]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.4527],
        [0.4426],
        [0.4611],
        [0.4368],
        [0.4476]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [21]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.8822,  0.6972,  0.7013, -1.6710, -0.0808,  2.2259],
        [ 1.6340,  0.9453, -0.0686, -0.9371, -0.9500, -0.3982],
        [ 0.4733,  0.8804,  0.2565,  1.9115,  2.7115,  0.0715],
        [-0.9759, -0.3215, -0.4671, -0.7215,  1.4857,  2.1885],
        [-1.7061,  1.7265,  1.0250, -0.7325,  0.2632, -0.0362]])

In [22]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.5724, 0.2615, 0.1661],
        [0.5193, 0.3005, 0.1802],
        [0.2064, 0.4444, 0.3492],
        [0.4184, 0.3436, 0.2380],
        [0.6637, 0.2043, 0.1320]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [23]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[-0.2197,  0.4656,  0.7311, -0.4890, -0.1865,  0.2628],
        [-0.6357,  0.6359, -0.8352,  1.9917, -1.7162, -1.7622],
        [-0.2936,  0.9404,  0.4712,  1.0225, -0.7052,  2.2481],
        [-0.9935,  0.1380, -0.6307, -0.0478, -0.7854, -0.5751],
        [ 1.1280,  0.5450,  0.4442, -0.6266,  0.7830, -0.9888]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[-0.8303],
        [-0.0157],
        [-1.1939],
        [-0.4187],
        [-0.2276]], grad_fn=<AddmmBackward0>)

## Loss Functions

### Transforming Labels with One-hot Encoding

In [25]:
from torch import tensor
import torch.nn.functional as F

F.one_hot(tensor([0, 1, 2]), num_classes=3)

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

### Cross Entropy Loss

In [26]:
from torch import tensor, nn

y_hat = tensor([[-5.2, 4.6, 0.8]])
y_hat

tensor([[-5.2000,  4.6000,  0.8000]])

In [27]:
y = tensor([0])
one_hot_y = F.one_hot(y, num_classes=3)
one_hot_y

tensor([[1, 0, 0]])

In [28]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(y_hat.double(), one_hot_y.double())
loss

tensor(9.8222, dtype=torch.float64)

## Sample Dataset

#### Load sample dataset

In [29]:
import pandas as pd

animals = pd.read_csv("animal_dataset.csv")
animals

animal_name   hair   feathers   eggs   milk   predator   legs   tail   type
0     sparrow      0          1      1      0          0      2      1      0
1       eagle      0          1      1      0          1      2      1      0
2         cat      1          0      0      1          1      4      1      1
3         dog      1          0      0      1          0      4      1      1
4      lizard      0          0      1      0          1      4      1      2

#### Features

In [30]:
features = animals.iloc[:, 1:-1]
features

hair  feathers  eggs  milk  predator  legs  tail
0     0         1     1     0         0     2     1
1     0         1     1     0         1     2     1
2     1         0     0     1         1     4     1
3     1         0     0     1         0     4     1
4     0         0     1     0         1     4     1

In [31]:
X = features.to_numpy()
X

array([[0, 1, 1, 0, 0, 2, 1],
       [0, 1, 1, 0, 1, 2, 1],
       [1, 0, 0, 1, 1, 4, 1],
       [1, 0, 0, 1, 0, 4, 1],
       [0, 0, 1, 0, 1, 4, 1]])

#### Target Values

In [32]:
target = animals.iloc[:, -1]
target

0    0
1    0
2    1
3    1
4    2
Name:  type, dtype: int64

In [33]:
y = target.to_numpy()
y

array([0, 0, 1, 1, 2])

#### TensorDataset

In [34]:
from torch.utils.data import TensorDataset
from torch import tensor

dataset = TensorDataset(tensor(X), tensor(y))
dataset

In [35]:
input_sample, label_sample = dataset[0]
print(f"input_sample: {input_sample}")
print(f"label_sample: {label_sample}")

input_sample: tensor([0, 1, 1, 0, 0, 2, 1])
label_sample: 0


#### DataLoader

In [36]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size=2, shuffle=True)

In [37]:
for batch_inputs, batch_labels in dataloader:
    print(f"batch_inputs: {batch_inputs}")
    print(f"batch_labels: {batch_labels}")
    print("=" * 50)

batch_inputs: tensor([[1, 0, 0, 1, 0, 4, 1],
        [0, 1, 1, 0, 0, 2, 1]])
batch_labels: tensor([1, 0])
batch_inputs: tensor([[0, 1, 1, 0, 1, 2, 1],
        [1, 0, 0, 1, 1, 4, 1]])
batch_labels: tensor([0, 1])
batch_inputs: tensor([[0, 0, 1, 0, 1, 4, 1]])
batch_labels: tensor([2])


## Training Loop

### Load Salary Dataset

In [38]:
import pandas as pd

salary = pd.read_csv("salary_dataset.csv")
salary

experience_level   employment_type   remote_ratio   company_size  \
0                 0                 0            0.5              1   
1                 1                 0            1.0              2   
2                 2                 0            0.0              1   
3                 1                 0            1.0              0   
4                 2                 0            1.0              1   

    salary_in_usd  
0           0.036  
1           0.133  
2           0.234  
3           0.076  
4           0.170

### Features & Target

In [39]:
features = salary.iloc[:, :-1]
features

experience_level   employment_type   remote_ratio   company_size
0                 0                 0            0.5              1
1                 1                 0            1.0              2
2                 2                 0            0.0              1
3                 1                 0            1.0              0
4                 2                 0            1.0              1

In [40]:
X = features.to_numpy()
X

array([[0. , 0. , 0.5, 1. ],
       [1. , 0. , 1. , 2. ],
       [2. , 0. , 0. , 1. ],
       [1. , 0. , 1. , 0. ],
       [2. , 0. , 1. , 1. ]])

In [41]:
target = salary.iloc[:, -1]
target

0    0.036
1    0.133
2    0.234
3    0.076
4    0.170
Name:  salary_in_usd, dtype: float64

In [42]:
y = target.to_numpy()
y

array([0.036, 0.133, 0.234, 0.076, 0.17 ])

### Tensor Dataset & DataLoader

In [43]:
from torch.utils.data import TensorDataset, DataLoader
from torch import tensor

dataset = TensorDataset(tensor(X).float(), tensor(y).float())
dataset

In [44]:
dataloader = DataLoader(dataset, batch_size=4, shuffle=True)

### Model, Loss Function & Optimizer

In [45]:
from torch import nn, optim

model = nn.Sequential(nn.Linear(4, 2), nn.Linear(2, 1))
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

### The Training Loop

In [46]:
num_epochs = 10

for epoch in range(num_epochs):
    for data in dataloader:
        optimizer.zero_grad()
        feature, target = data
        pred = model(feature)
        loss = criterion(pred, target)
        loss.backward()
        optimizer.step()

/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([4])) that is different to the input size (torch.Size([4, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
