# Introduction to Pytorch

## The Basics

In [1]:
# !pip install requirements.txt

### Tensor

In [2]:
from torch import tensor

/Users/setiabudi/opt/miniconda3/envs/pytorch312/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [3]:
input_tensor = tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
input_tensor

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [4]:
input_tensor.shape

torch.Size([2, 3])

In [5]:
input_tensor.dtype

torch.float32

### Linear Layer

In [6]:
from torch import nn

In [7]:
linear_layer = nn.Linear(in_features=3, out_features=2)
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [8]:
linear_layer.weight

Parameter containing:
tensor([[-0.4338, -0.3932,  0.3115],
        [ 0.2476,  0.0014, -0.1208]], requires_grad=True)

In [9]:
linear_layer.bias

Parameter containing:
tensor([ 0.0589, -0.5622], requires_grad=True)

In [10]:
output = linear_layer(input_tensor)
output

tensor([[-0.2267, -0.6742],
        [-1.7732, -0.2895]], grad_fn=<AddmmBackward0>)

### Stacking Layers

In [11]:
from torch import nn

In [12]:
n_features = 3
n_output = 2

model = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=8),
    nn.Linear(in_features=8, out_features=4),
    nn.Linear(in_features=4, out_features=n_output),
)
model

Sequential(
  (0): Linear(in_features=3, out_features=8, bias=True)
  (1): Linear(in_features=8, out_features=4, bias=True)
  (2): Linear(in_features=4, out_features=2, bias=True)
)

### Model Parameters

In [13]:
from torch import nn

model = nn.Sequential(nn.Linear(3, 8), nn.Linear(8, 4), nn.Linear(4, 2))

In [14]:
total_params = 0
for parameter in model.parameters():
    # print(parameter)
    print(parameter.numel())
    print("=" * 50)
    total_params += parameter.numel()

print(f"Total parameters: {total_params}")

24
8
32
4
8
2
Total parameters: 78


## Neural Networks Architecture

### Activation Layer: Sigmoid Function

In [15]:
from torch import tensor, nn

input_tensor = tensor([[6.0]])
input_tensor

tensor([[6.]])

In [16]:
sigmoid_layer = nn.Sigmoid()
sigmoid_layer(input_tensor)

tensor([[0.9975]])

### Activation Layer: Softmax Function

In [17]:
from torch import tensor, nn

input_tensor = tensor([[4.3, 6.1, 2.3]])
input_tensor

tensor([[4.3000, 6.1000, 2.3000]])

In [18]:
softmax_layer = nn.Softmax(dim=-1)
softmax_layer(input_tensor)

tensor([[0.1392, 0.8420, 0.0188]])

### Forward Pass: Binary Classification

In [19]:
from torch import tensor, nn, randn

input_tensor = randn(
    5, 6
)  # Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor

tensor([[ 1.1832, -0.2454,  0.0098,  0.9066,  0.7109,  0.4908],
        [-1.9120,  0.2175, -1.4223, -0.4514, -0.7435,  1.6976],
        [-1.8321, -1.5117,  0.5538, -1.7334,  1.2498,  0.6079],
        [ 0.1668, -0.7673,  0.4914,  0.9650,  0.0049,  0.2820],
        [-0.7427, -0.3352, -0.0986, -0.1937, -0.9433,  0.4315]])

In [20]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
    nn.Sigmoid(),  # Sigmoid Activation Function
)

model(input_tensor)

tensor([[0.2692],
        [0.4297],
        [0.4358],
        [0.2761],
        [0.3784]], grad_fn=<SigmoidBackward0>)

### Forward Pass: Multi-class Classification

In [21]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.6308, -0.2766,  0.5657, -1.7294, -0.8661,  0.8188],
        [-0.0829, -0.8862,  0.9242, -1.5241, -1.2096, -0.4663],
        [ 1.2548, -1.5524, -0.6651,  0.2778,  0.8066, -0.4483],
        [-0.2180,  0.5177,  0.1046,  0.2174,  0.2837, -1.9980],
        [-1.0653, -0.1309,  0.2402,  0.7892, -0.2004, -0.0625]])

In [22]:
n_classes = 3

model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=n_classes),  # Second Linear Layer
    nn.Softmax(dim=-1),  # Softmax Activation Function
)

model(input_tensor)

tensor([[0.4919, 0.2480, 0.2601],
        [0.5102, 0.2308, 0.2590],
        [0.2996, 0.3135, 0.3869],
        [0.3573, 0.3160, 0.3267],
        [0.3061, 0.3925, 0.3014]], grad_fn=<SoftmaxBackward0>)

### Forward Pass: Regression

In [23]:
from torch import tensor, nn, randn

# Creates a tensor of shape (5, 6) with random values from normal distribution
input_tensor = randn(5, 6)
input_tensor

tensor([[ 0.8361, -0.6867, -2.7787,  0.6003, -0.3717,  0.0365],
        [ 0.7809, -1.3208,  0.5970, -1.3697,  0.1783, -0.1608],
        [ 0.9965, -0.1396, -1.1461,  0.6720,  0.2650,  1.0886],
        [-0.5829, -1.6600, -0.0201, -0.5843, -0.9979, -1.7501],
        [-0.4984,  0.3717,  1.8326, -0.2297,  0.8933,  3.2107]])

In [24]:
model = nn.Sequential(
    nn.Linear(in_features=6, out_features=4),  # First Linear Layer
    nn.Linear(in_features=4, out_features=1),  # Second Linear Layer
)

model(input_tensor)

tensor([[ 0.2119],
        [-0.0668],
        [ 0.0828],
        [ 0.2221],
        [ 0.1383]], grad_fn=<AddmmBackward0>)